import json
import sys
import subprocess
import os
from datetime import datetime, timedelta
from github import Github

def generate_markdown_table(stats_list, org_name, start_date, end_date):
    """
    Generate a markdown table from issue statistics.
    
    Args:
        stats_list (list): List of statistics dictionaries from GitHubIssuesAnalyzer
        org_name (str): Name of the GitHub organization
        start_date (str): Start date of the report period
        end_date (str): End date of the report period
        
    Returns:
        str: Markdown formatted table
    """
    markdown = "---\n"
    markdown += "title: Archival Candidates Report\n"
    markdown += "labels: archival, automated\n"
    markdown += "---\n\n"
    markdown += f"# {org_name} Repository Archival Candidates Report\n\n"
    markdown += "This report was automatically generated by the [archival-identifier](https://github.com/DSACMS/archival-identifier) tool to identify potential archival candidates based on:"
    markdown += "\n- Development activity\n- Reuse via forks\n- [OpenSSF Criticality Score](https://github.com/ossf/criticality_score)\n- Repository Contents\n\n"
    markdown += "For more information about the criteria used to determine archival candidacy, please refer to the [archival-identifier documentation](https://github.com/DSACMS/archival-identifier).\n\n"
    markdown += f"## Results: {start_date} to {end_date}\n\n"
    markdown += "| Repository | Open Issues | Closed Issues | Open PRs | Merged PRs | Closed PRs | Releases | Commits | Criticality Score | Forks | Active Forks | Is Empty/README-Only | Status |\n"
    markdown += "|---|---|---|---|---|---|---|---|---|---|---|---|---|\n"
    
    for repo, stats in stats_list.items():
        markdown += f"| {repo} | {stats['issues_open_count']} | {stats['issues_closed_count']} | {stats['pr_open_count']} | {stats['pr_merged_count']} | {stats['pr_closed_count']} | {stats['release_count']} | {stats['commit_count']} | {stats['criticality_score']} | {stats['forks_count']} | {stats['active_forks_count']} | {stats['is_empty_or_readme_only']} | {stats['status']} |\n"
    
    return markdown

def write_markdown_file(markdown_content, output_path="archival_candidates_report.md"):
    """
    Write markdown content to a file.
    
    Args:
        markdown_content (str): The markdown content to write
        output_path (str): Path where the markdown file should be saved
    """
    with open(output_path, 'w') as f:
        f.write(markdown_content)
    print(f"Markdown report written to {output_path}")

def get_criticality_score(org_name, repo_name):
    """See https://github.com/ossf/criticality_score for more details on the OpenSSF Criticality Score.
    
    org_name (str)
    repo_name (str)
    
    criticality_score (str): This value ranges from 0 to 1 (like a float) with lower scores indicating less critical projects.
    
    """

    repo_url = f"github.com/{org_name}/{repo_name}"
    cmd_str = f'criticality_score --repo {repo_url} --format csv'

    try:
        proc = subprocess.Popen(cmd_str, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
        out, err = proc.communicate()
        print(out.decode("utf-8"))
        print(err)
        
        if not err:
            csv_str = out.decode("utf-8")
            items = csv_str.split(',')
            criticality_score = items[26].rstrip()
        else: 
            criticality_score = None
    except:
        criticality_score = None

    return criticality_score

def define_status_determination(stats):
    """
    Determine the status of a repository based on its statistics.
    
    stats (dict): A dictionary containing development activity statistics for a repository
        
    str: The determined status of the repository (e.g., "Active", "Dormant")
    """
    # Placeholder logic for status determination
    if all(stats.get(field, 0) == 0 for field in [
        "issues_open_count",
        "issues_closed_count",
        "pr_open_count",
        "pr_merged_count",
        "pr_closed_count",
        "release_count",
        "commit_count",
        "active_forks_count"
    ]):
        return "Dormant"
    else:
        return "Active"

def analyze_fork_activity(repo, start_date, end_date):
    """
    Analyze the activity of forks for a given repository.
    
    repo (str): name of repository
    start_date (str): start date for the reporting period (YYYY-MM-DD)
    end_date (str): end date for the analysis period (YYYY-MM-DD)
    
    dict: A dictionary containing statistics about the forks (e.g., number of forks, recent activity)
    """

    g = Github(os.getenv("GITHUB_AUTH_TOKEN"))
    org_name = os.getenv("ORG_NAME")
    
    start_date = datetime.strptime(start_date, "%Y-%m-%d")
    end_date = datetime.strptime(end_date, "%Y-%m-%d")

    repo_obj = g.get_repo(f"{org_name}/{repo}")
    forks = list(repo_obj.get_forks())
    forks_count = len(forks)
    print( f"{repo} has {forks_count} forks.")
    active_forks = []

    for fork in forks:
        print(f"Analyzing fork: {fork.full_name}...")
        
        # Then check if fork has diverged / has unique commits
        try:
            # Compare the parent's default branch with the fork's default branch
            parent_sha =repo_obj.get_branch("main").commit.sha
            fork_sha = fork.get_branch("main").commit.sha
            print("parent sha " + parent_sha)
            print("fork sha " + fork_sha)

            # Determine whether the fork has diverged from the parent repository
            if fork_sha != parent_sha:
                print("diverged")
                
                # Check if there are recent commits within the reporting period
                recent_commits = fork.get_commits(since=start_date, until=end_date)
                count = recent_commits.totalCount
                print("recent commits: " + str(count))
                
                active_forks.append(fork)
            else:
                print("identical")

        except Exception as e:
            # Fork has an empty default branch or encountered other issues. Classify as inactive.
            if e.status == 404:
                print("Error")
            else:
                print(f"\nCould not compare {fork.full_name}: {e}")
        
    print(f"{len(active_forks)} active forks found for {repo}.")
    return forks_count, len(active_forks)


def main():

    #Setting variables from environment and command line arguments
    org_name = os.getenv("ORG_NAME")
    start_date = os.getenv("START_DATE")
    end_date = os.getenv("END_DATE") or datetime.now().strftime("%Y-%m-%d")
    
    print(start_date)
    print(end_date)

    development_activity_file = sys.argv[1]
    empty_repo_report_file = sys.argv[2]

    with open(development_activity_file, 'r') as f:
        data = json.load(f)

    with open(empty_repo_report_file, 'r') as f:
        empty_repo_data = json.load(f)
    print (empty_repo_data)

    stats= {}

    for repo in data["repos"]:
        print(f"Analyzing {repo['name']}: Development Activity")

        # Calculate statistics for the repository
        stats[repo["name"]] = {
            "issues_open_count": len([issue for issue in repo["issues"] if issue["state"] == "open"]),
            "issues_closed_count": len([issue for issue in repo["issues"] if issue["state"] == "closed"]),
            # TODO: for pulls, add the author github-actions[bot] dependabot[bot]
            # TODO: filter pulls by author and mentions of "code.json" in the title
            "pr_open_count": len([pr for pr in repo["pulls"] if pr["state"] == "open"]),
            "pr_merged_count": len([pr for pr in repo["pulls"] if pr["state"] == "closed" and pr["merged"] == True]),
            "pr_closed_count": len([pr for pr in repo["pulls"] if pr["state"] == "closed" and pr["merged"] == False]),
            "release_count": len(repo["releases"]),
            "commit_count": len([commit for commit in repo["commits"] if commit["author"] != "dependabot[bot]" and commit["author"] != "github-actions[bot]"])
        }

        # Run OpenSSF Criticality Score
        print(f"Analyzing {repo['name']}: Criticality Score")
        criticality_score = get_criticality_score(os.getenv("ORG_NAME"), repo["name"])
        stats[repo["name"]]["criticality_score"] = criticality_score # criticality_score

        # TODO: Analyze fork activity
        print(f"Analyzing {repo['name']}: Usage via forks")
        forks_count, active_forks_count = analyze_fork_activity(repo["name"], start_date, end_date)
        stats[repo["name"]]["forks_count"] = forks_count
        stats[repo["name"]]["active_forks_count"] = active_forks_count

        ## TODO: Analyze repository contents (e.g., is it empty or README-only)
        print(f"Analyzing {repo['name']}: Repository contents")
        repo_full_name = f"{org_name}/{repo['name']}"
        if repo_full_name in empty_repo_data.get("readmeOnly", []):
            stats[repo["name"]]["is_empty_or_readme_only"] = "README-only"
        elif repo_full_name in empty_repo_data.get("empty", []):
            stats[repo["name"]]["is_empty_or_readme_only"] = "Empty"
        else:
            stats[repo["name"]]["is_empty_or_readme_only"] = "No"

        # Determine the status of the repository
        stats[repo["name"]]["status"] = define_status_determination(stats[repo["name"]])

    # print(stats)

    # Generate and write markdown file
    markdown_content = generate_markdown_table(stats, org_name, start_date, end_date)
    write_markdown_file(markdown_content)

if __name__ == "__main__":
    main()
